branch-defaults:
  fix-aws:
    environment: flask-env
  master:
    environment: flask-env
    group_suffix: null
global:
  application_name: backstop
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
